export const CREATE_MESSAGE = 'POST/CREATE_MESSAGE'
export const FETCH_MESSAGE = 'POST/FETCH_MESSAGE'

export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'

export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/HIDE_ALERT'

export const SHOW_LAYOUT = 'SHOW_LAYOUT'
export const REGION_ROOT = 'REGION_ROOT'
export const REGION_MAIN = 'REGION_MAIN'
export const REGION_SIDEBAR = 'REGION_SIDEBAR'

export const REQUEST_CHATID = 'REQUEST_CHATID'
export const REQUEST_CHATS = 'REQUEST_CHATS'
export const FETCHED_CHATID = 'FETCHED_CHATID'
export const FETCHED_MESSAGES = 'FETCHED_MESSAGES'
export const FETCHED_CHATS = 'FETCHED_CHATS'