export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'

export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/HIDE_ALERT'

export const SHOW_LAYOUT = 'APP/SHOW_LAYOUT'
export const REGION_ROOT = 'APP/LAYOUT/REGION_ROOT'
export const REGION_MAIN = 'APP/LAYOUT/REGION_MAIN'
export const REGION_SIDEBAR = 'APP/LAYOUT/REGION_SIDEBAR'

export const REQUEST_CHATID = 'CHAT/REQUEST_CHATID'
export const REQUEST_CHATS = 'CHAT/REQUEST_CHATS'
export const FETCHED_CHATID = 'CHAT/FETCHED_CHATID'
export const FETCHED_CHATS = 'CHAT/FETCHED_CHATS'
export const FETCHED_MESSAGES = 'CHAT/FETCHED_MESSAGES'

export const USER_LOGIN = 'USER/LOGIN'
export const USER_LOGOUT = 'USER/LOGOUT/CLEAR_STATE'