import useVisibilityChange from "../hooks/useVisibilityChange";

export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'

export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/HIDE_ALERT'

export const SHOW_LAYOUT = 'APP/SHOW_LAYOUT'
export const REGION_ROOT = 'APP/LAYOUT/REGION_ROOT'
export const REGION_CHAT = 'APP/LAYOUT/REGION_CHAT'
export const REGION_ROOMLIST = 'APP/LAYOUT/REGION_ROOMLIST'

export const VISIBILITY_CHANGE = 'APP/VISIBILITY_CHANGE'

export const USER_LOGIN = 'AUTH/LOGIN'
export const USER_LOGOUT = 'AUTH/LOGOUT/CLEAR_STATE'

//___CHATS___
export const CHAT_USER_UPDATE = 'CHAT/CHAT_USER_UPDATE'
export const CHAT_USER_EXIT = 'CHAT/CHAT_USER_EXIT'

export const REQUEST_USERROOMS_METADATA = 'CHAT/REQUEST_USERROOMS_METADATA'
export const UPDATE_USERROOMS_METADATA = 'CHAT/UPDATE_USERROOMS_METADATA'

export const REQUEST_ROOMID_METADATA = 'CHAT/REQUEST_ROOMID_METADATA'
export const UPDATE_ROOMID_METADATA = 'CHAT/UPDATE_ROOMID_METADATA'

export const REQUEST_ROOMID_MESSAGES = 'CHAT/REQUEST_ROOMID_MESSAGES'
export const UPDATE_ROOMID_MESSAGES = 'CHAT/UPDATE_ROOMID_MESSAGES'
export const UPDATE_ROOMID_MESSAGES_STATUSES = 'CHAT/UPDATE_ROOMID_MESSAGES_STATUSES'

export const ALL_REQUEST_WITH_THE_CURRENT_ROOM_ARE_COMPLETED = 'CHAT/ALL_REQUEST_WITH_THE_CURRENT_ROOM_ARE_COMPLETED'

export const CITATION_SET = 'CHAT/CITATION_SET'
export const CITATION_CLEAR = 'CHAT/CITATION_CLEAR'

export const ADD_NEW_MESSAGE_IN_CURRENT_CHAT = 'CHAT/ADD_NEW_MESSAGE_IN_CURRENT_CHAT'
export const MODIFY_MESSAGE_IN_CURRENT_CHAT = 'CHAT/MODIFY_MESSAGE_IN_CURRENT_CHAT'
export const REMOVE_MESSAGE_IN_CURRENT_CHAT = 'CHAT/REMOVE_MESSAGE_IN_CURRENT_CHAT'
export const ADD_NEW_MESSAGE_IN_OTHER_CHAT = 'CHAT/ADD_NEW_MESSAGE_IN_OTHER_CHAT'
//export const MODIFY_MESSAGE_IN_OTHER_CHAT = 'CHAT/MODIFY_MESSAGE_IN_OTHER_CHAT'
//export const REMOVE_MESSAGE_IN_OTHER_CHAT = 'CHAT/REMOVE_MESSAGE_IN_OTHER_CHAT'

export const ADD_NEW_MESSAGE_STATUS_IN_CURRENT_CHAT = 'CHAT/ADD_NEW_MESSAGE_STATUS_IN_CURRENT_CHAT'
export const MODIFY_MESSAGE_STATUS_IN_CURRENT_CHAT = 'CHAT/MODIFY_MESSAGE_STATUS_IN_CURRENT_CHAT'
export const REMOVE_MESSAGE_STATUS_IN_CURRENT_CHAT = 'CHAT/REMOVE_MESSAGE_STATUS_IN_CURRENT_CHAT'
export const ADD_NEW_MESSAGE_STATUS_IN_OTHER_CHAT = 'CHAT/ADD_NEW_MESSAGE_STATUS_IN_OTHER_CHAT'
//export const MODIFY_MESSAGE_STATUS_IN_OTHER_CHAT = 'CHAT/MODIFY_MESSAGE_STATUS_IN_OTHER_CHAT'
//export const REMOVE_MESSAGE_STATUS_IN_OTHER_CHAT = 'CHAT/REMOVE_MESSAGE_STATUS_IN_OTHER_CHAT'

export const REQUEST_USERROOMS_UNREAD_MESSAGES = 'CHAT/REQUEST_USERROOMS_UNREAD_MESSAGES'
export const UPDATE_USERROOMS_UNREAD_MESSAGES = 'CHAT/UPDATE_USERROOMS_UNREAD_MESSAGES'

/*export const ENTER_ROOM = 'CHAT/ENTER_ROOM'*/
export const EXIT_ROOM = 'CHAT/EXIT_ROOM'

export const REQUEST_USER_CONTACTS = 'CHAT/REQUEST_USER_CONTACTS'
export const UPDATE_USER_CONTACTS = 'CHAT/UPDATE_USER_CONTACTS'
